import { Injectable } from '@angular/core';

import { Product } from '../@entities/product';

@Injectable({
  providedIn: 'root',
})
export class DummyDataService {
  public categoryList: string[] = [
    'all menu',
    'appetizer',
    'seafood',
    'chicken',
    'beef',
    'vegetables',
    'drink',
    'dessert',
    'beverages',
    'cocktail',
  ];

  public productList: Product[] = [
    // Appetizer
    {
      id: 1,
      name: 'Spring Rolls',
      category: 'appetizer',
      price: 25000,
      amount: 0,
    },
    {
      id: 2,
      name: 'Garlic Bread',
      category: 'appetizer',
      price: 20000,
      amount: 0,
    },
    {
      id: 3,
      name: 'Bruschetta',
      category: 'appetizer',
      price: 28000,
      amount: 0,
    },
    {
      id: 4,
      name: 'Chicken Wings',
      category: 'appetizer',
      price: 35000,
      amount: 0,
    },
    {
      id: 5,
      name: 'Stuffed Mushrooms',
      category: 'appetizer',
      price: 30000,
      amount: 0,
    },
    {
      id: 6,
      name: 'Nachos with Cheese',
      category: 'appetizer',
      price: 40000,
      amount: 0,
    },
    {
      id: 7,
      name: 'Deviled Eggs',
      category: 'appetizer',
      price: 22000,
      amount: 0,
    },
    {
      id: 8,
      name: 'Caprese Salad',
      category: 'appetizer',
      price: 27000,
      amount: 0,
    },
    {
      id: 9,
      name: 'Mini Quiches',
      category: 'appetizer',
      price: 32000,
      amount: 0,
    },
    {
      id: 10,
      name: 'Mozzarella Sticks',
      category: 'appetizer',
      price: 30000,
      amount: 0,
    },

    // Seafood
    {
      id: 11,
      name: 'Grilled Salmon',
      category: 'seafood',
      price: 85000,
      amount: 0,
    },
    {
      id: 12,
      name: 'Garlic Butter Shrimp',
      category: 'seafood',
      price: 75000,
      amount: 0,
    },
    {
      id: 13,
      name: 'Fried Calamari',
      category: 'seafood',
      price: 65000,
      amount: 0,
    },
    {
      id: 14,
      name: 'Fish Tacos',
      category: 'seafood',
      price: 70000,
      amount: 0,
    },
    {
      id: 15,
      name: 'Crab Cakes',
      category: 'seafood',
      price: 80000,
      amount: 0,
    },
    {
      id: 16,
      name: 'Lobster Bisque',
      category: 'seafood',
      price: 90000,
      amount: 0,
    },
    {
      id: 17,
      name: 'Seared Scallops',
      category: 'seafood',
      price: 88000,
      amount: 0,
    },
    {
      id: 18,
      name: 'Oysters Rockefeller',
      category: 'seafood',
      price: 95000,
      amount: 0,
    },
    {
      id: 19,
      name: 'Fish and Chips',
      category: 'seafood',
      price: 70000,
      amount: 0,
    },
    {
      id: 20,
      name: 'Seafood Paella',
      category: 'seafood',
      price: 100000,
      amount: 0,
    },

    // Chicken
    {
      id: 21,
      name: 'Grilled Chicken',
      category: 'chicken',
      price: 70000,
      amount: 0,
    },
    {
      id: 22,
      name: 'Chicken Alfredo',
      category: 'chicken',
      price: 75000,
      amount: 0,
    },
    {
      id: 23,
      name: 'Chicken Tikka Masala',
      category: 'chicken',
      price: 80000,
      amount: 0,
    },
    {
      id: 24,
      name: 'Fried Chicken',
      category: 'chicken',
      price: 60000,
      amount: 0,
    },
    {
      id: 25,
      name: 'Chicken Caesar Salad',
      category: 'chicken',
      price: 50000,
      amount: 0,
    },
    {
      id: 26,
      name: 'Buffalo Chicken Wrap',
      category: 'chicken',
      price: 55000,
      amount: 0,
    },
    {
      id: 27,
      name: 'Chicken Teriyaki',
      category: 'chicken',
      price: 80000,
      amount: 0,
    },
    {
      id: 28,
      name: 'Lemon Herb Chicken',
      category: 'chicken',
      price: 70000,
      amount: 0,
    },
    {
      id: 29,
      name: 'Chicken Satay',
      category: 'chicken',
      price: 75000,
      amount: 0,
    },
    {
      id: 30,
      name: 'Chicken Parmesan',
      category: 'chicken',
      price: 80000,
      amount: 0,
    },

    // Beef
    { id: 31, name: 'Beef Steak', category: 'beef', price: 120000, amount: 0 },
    { id: 32, name: 'Beef Rendang', category: 'beef', price: 90000, amount: 0 },
    {
      id: 33,
      name: 'Beef Stroganoff',
      category: 'beef',
      price: 95000,
      amount: 0,
    },
    { id: 34, name: 'Beef Burger', category: 'beef', price: 75000, amount: 0 },
    { id: 35, name: 'Beef Tacos', category: 'beef', price: 80000, amount: 0 },
    {
      id: 36,
      name: 'Beef Brisket',
      category: 'beef',
      price: 110000,
      amount: 0,
    },
    {
      id: 37,
      name: 'Beef Wellington',
      category: 'beef',
      price: 150000,
      amount: 0,
    },
    { id: 38, name: 'Beef Bulgogi', category: 'beef', price: 85000, amount: 0 },
    { id: 39, name: 'Beef Kebab', category: 'beef', price: 70000, amount: 0 },
    { id: 40, name: 'Beef Lasagna', category: 'beef', price: 80000, amount: 0 },

    // Vegetables
    {
      id: 41,
      name: 'Stir-Fried Vegetables',
      category: 'vegetables',
      price: 40000,
      amount: 0,
    },
    {
      id: 42,
      name: 'Grilled Asparagus',
      category: 'vegetables',
      price: 45000,
      amount: 0,
    },
    {
      id: 43,
      name: 'Caesar Salad',
      category: 'vegetables',
      price: 35000,
      amount: 0,
    },
    {
      id: 44,
      name: 'Vegetable Curry',
      category: 'vegetables',
      price: 50000,
      amount: 0,
    },
    {
      id: 45,
      name: 'Ratatouille',
      category: 'vegetables',
      price: 55000,
      amount: 0,
    },
    {
      id: 46,
      name: 'Vegetable Tempura',
      category: 'vegetables',
      price: 45000,
      amount: 0,
    },
    {
      id: 47,
      name: 'Creamed Spinach',
      category: 'vegetables',
      price: 40000,
      amount: 0,
    },
    {
      id: 48,
      name: 'Grilled Zucchini',
      category: 'vegetables',
      price: 40000,
      amount: 0,
    },
    {
      id: 49,
      name: 'Vegetable Stir-Fry',
      category: 'vegetables',
      price: 42000,
      amount: 0,
    },
    {
      id: 50,
      name: 'Mixed Green Salad',
      category: 'vegetables',
      price: 35000,
      amount: 0,
    },

    // Drink
    { id: 51, name: 'Lemonade', category: 'drink', price: 20000, amount: 0 },
    { id: 52, name: 'Iced Tea', category: 'drink', price: 15000, amount: 0 },
    {
      id: 53,
      name: 'Mineral Water',
      category: 'drink',
      price: 10000,
      amount: 0,
    },
    { id: 54, name: 'Coke', category: 'drink', price: 18000, amount: 0 },
    { id: 55, name: 'Sprite', category: 'drink', price: 18000, amount: 0 },
    {
      id: 56,
      name: 'Orange Juice',
      category: 'drink',
      price: 25000,
      amount: 0,
    },
    { id: 57, name: 'Apple Juice', category: 'drink', price: 25000, amount: 0 },
    { id: 58, name: 'Ginger Ale', category: 'drink', price: 20000, amount: 0 },
    {
      id: 59,
      name: 'Pineapple Juice',
      category: 'drink',
      price: 25000,
      amount: 0,
    },
    {
      id: 60,
      name: 'Coconut Water',
      category: 'drink',
      price: 20000,
      amount: 0,
    },

    // Dessert
    {
      id: 61,
      name: 'Chocolate Cake',
      category: 'dessert',
      price: 40000,
      amount: 0,
    },
    { id: 62, name: 'Ice Cream', category: 'dessert', price: 30000, amount: 0 },
    { id: 63, name: 'Tiramisu', category: 'dessert', price: 50000, amount: 0 },
    {
      id: 64,
      name: 'Cheesecake',
      category: 'dessert',
      price: 45000,
      amount: 0,
    },
    { id: 65, name: 'Brownies', category: 'dessert', price: 35000, amount: 0 },
    {
      id: 66,
      name: 'Panna Cotta',
      category: 'dessert',
      price: 50000,
      amount: 0,
    },
    {
      id: 67,
      name: 'Fruit Salad',
      category: 'dessert',
      price: 30000,
      amount: 0,
    },
    {
      id: 68,
      name: 'Creme Brulee',
      category: 'dessert',
      price: 45000,
      amount: 0,
    },
    { id: 69, name: 'Pavlova', category: 'dessert', price: 40000, amount: 0 },
    {
      id: 70,
      name: 'Banana Split',
      category: 'dessert',
      price: 30000,
      amount: 0,
    },

    // Beverages
    {
      id: 71,
      name: 'Espresso',
      category: 'beverages',
      price: 25000,
      amount: 0,
    },
    { id: 72, name: 'Latte', category: 'beverages', price: 30000, amount: 0 },
    {
      id: 73,
      name: 'Cappuccino',
      category: 'beverages',
      price: 30000,
      amount: 0,
    },
    {
      id: 74,
      name: 'Hot Chocolate',
      category: 'beverages',
      price: 25000,
      amount: 0,
    },
    {
      id: 75,
      name: 'Matcha Latte',
      category: 'beverages',
      price: 35000,
      amount: 0,
    },
    {
      id: 76,
      name: 'Chai Tea',
      category: 'beverages',
      price: 25000,
      amount: 0,
    },
    {
      id: 77,
      name: 'Americano',
      category: 'beverages',
      price: 20000,
      amount: 0,
    },
    { id: 78, name: 'Mocha', category: 'beverages', price: 30000, amount: 0 },
    {
      id: 79,
      name: 'Flat White',
      category: 'beverages',
      price: 30000,
      amount: 0,
    },
    {
      id: 80,
      name: 'Black Coffee',
      category: 'beverages',
      price: 20000,
      amount: 0,
    },

    // Cocktail
    {
      id: 81,
      name: 'Margarita',
      category: 'cocktail',
      price: 60000,
      amount: 0,
    },
    { id: 82, name: 'Mojito', category: 'cocktail', price: 60000, amount: 0 },
    {
      id: 83,
      name: 'Pina Colada',
      category: 'cocktail',
      price: 65000,
      amount: 0,
    },
    {
      id: 84,
      name: 'Bloody Mary',
      category: 'cocktail',
      price: 70000,
      amount: 0,
    },
    { id: 85, name: 'Mai Tai', category: 'cocktail', price: 75000, amount: 0 },
    {
      id: 86,
      name: 'Old Fashioned',
      category: 'cocktail',
      price: 80000,
      amount: 0,
    },
    {
      id: 87,
      name: 'Cosmopolitan',
      category: 'cocktail',
      price: 70000,
      amount: 0,
    },
    {
      id: 88,
      name: 'Whiskey Sour',
      category: 'cocktail',
      price: 75000,
      amount: 0,
    },
    { id: 89, name: 'Martini', category: 'cocktail', price: 70000, amount: 0 },
    {
      id: 90,
      name: 'Long Island Iced Tea',
      category: 'cocktail',
      price: 80000,
      amount: 0,
    },
  ];

  constructor() {}
}
